			<?php		
			$oCommon = new CommonController();
			$bChkProjectInsert = $oCommon->checkPermission('PROJECT', 'f_insert');
			$bChkProjectUpdate = $oCommon->checkPermission('PROJECT', 'f_update');
			$bChkAssignmentView = $oCommon->checkPermission('ASSIGNMENT', 'f_view');
			$bChkAssignmentInsert = $oCommon->checkPermission('ASSIGNMENT', 'f_insert');
			$bChkAssignmentUpdate = $oCommon->checkPermission('ASSIGNMENT', 'f_update');
			$bChkAssignmentDelete = $oCommon->checkPermission('ASSIGNMENT', 'f_delete');
			?>
			<div id="show" class="bodycontainer">
			<?php
			$project_id = isset($this->oProject->project_id)?$oCommon->encodeKey($this->oProject->project_id):'';
			if ($bChkProjectInsert == true || $bChkProjectUpdate == true) {
				$url = $this->url(array('controller' => 'assignment', 'action' => 'index', 'pid' => $project_id), null, true);
				include_once APPLICATION_PATH . '/views/scripts/partials/project_detail.phtml';
			} else {
				$url = $this->url(array('controller' => 'assignment', 'action' => 'detail', 'pid' => $project_id), null, true);
				include_once APPLICATION_PATH . '/views/scripts/partials/project_viewdetail.phtml';
			}
			?>	
				<!-- Client Spreadsheet Information -->	
				<?php include_once 'menu.phtml';?>
				<?php if ($bChkAssignmentView == true) {?>
				<script type="text/javascript">
				   $(document).ready(function(){
					   <?php if ($bChkAssignmentInsert == false) {?>
						    $("#btnCreateNew").attr('disabled', 'disabled');
						<?php }?>
						<?php if ($bChkAssignmentDelete == false) {?>
						    $("#btnDelete").attr('disabled', 'disabled');
						    $("input[type='checkbox']").attr('disabled', 'disabled');
						<?php }?>
				   });
				</script>
				<div>
					<?php
					$url = $this->url(array('controller' => 'assignment', 'action' => 'index', 'pid' => $project_id, 'cpage' => $this->countperpage), null, true);
					?>	
					<form name="frmSearch" id="frmSearch" method="POST" action="<?php echo $url?>">		
						<?php echo $this->formHidden('hidDel');?>
						<script>
							function doDelete(){
								var frm = document.frmSearch;
								frm.hidDel.value = selectChecked(document.frmSearch);
								frm.action = "<?php echo $this->url(array('controller' => 'assignment', 'action' => 'index', 'pid' => $project_id), null, true)?>";
								frm.submit();
							}
						</script>						
						<div class="idForCVpadding" style="width: 1024px; ">
							<div class="listviewBorder">
								<div class="listviewButtonLayer" style="width: 1024px; ">
									<div class="pwie">
										<table width="100%" border="0" cellpadding="0" cellspacing="0" class="lvblayerTable secContentbb">
											<tbody>
												<tr>
													<td width="868">
														<table border="0" cellspacing="0" cellpadding="0" align="left">
															<tbody>
																<tr>
																	<td class="pL10">
																		<input type="submit" id="btnDelete" name="btnDelete" class="button" value="Delete" onclick="doDelete()">
																	</td>
																	<td class="pL10">
																		<input type="button" id="btnCreateNew" name="btnCreateNew" class="button createNewBtn" value="New" onclick="javascript:location.href='<?php echo $this->url(array('controller' => 'assignment', 'action' => 'detail', 'pid' => $project_id), null, true)?>'">
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
													 
													<td width="36"><img src="<?php echo $this->baseUrl().'/public/images/spacer.gif';?>" class="advancedsearch floatR" border="0" align="absmiddle" title="Search" onclick="javascript:callAdvSearch('IP')"></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
								<table width="100%" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
									<tbody>
										<tr id="advancedSearch_showpickId_IP" height="35" width="100%" style="display:none;">
											<td colspan="5">
												<table border="0" width="100%" style="padding:5px">
													<tr>
														<td width="15%">IP Address</td>
														<td width="28%">
														<?php echo $this->form->getElement('ip_address_list_search'); ?>
														</td>
														<td width="16%">Assigned User</td>
														<td width="27%">
														<?php echo $this->form->getElement('username_assigned_search'); ?>
														</td>
													</tr>
													<tr>
														<td width="15%">Mnemonics</td>
														<td width="28%">
														<?php echo $this->form->getElement('mnemonics_list_search'); ?>
														</td>
														<td width="50%" colspan="2"></td>
													</tr>
													</table>
												</td>
												<td style="vertical-align: bottom; padding-bottom:5px">
													<?php echo $this->form->getElement('button-search'); ?>
												</td>
											</tr>
											</table>
											<div class="header">
												<div style="width: 1008px;">
													<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
														<thead>
															<tr class="tableHeadBg">
																<td width="2%">
																	<input type="checkbox" name="allcheck" onclick="selectAll(document.frmSearch)">
																</td>
																<td width="33%"> 
																	Assigned Users
																</td> 
																<td width="33%"> 
																	IP ranges
																</td>
																<td width="33%"> 
																	Mnemonics ranges
																</td>
															</tr>
														</thead>
													</table>
												</div>
												<div class="content">
													<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
														<tbody id="lvIP">
															<?php 
															if (count($this->paginator)):
																foreach ($this->paginator as $oObj):
																$project_ip_user_id = $oCommon->encodeKey($oObj['project_ip_user_id']);
																?>
																<tr id="ip1" class="tdout">
																	<td width="2%">
																		<input type="checkbox" name="chk" value="<?php echo $project_ip_user_id?>">
																	</td>
																	<td width="33%">
																		<a href="<?php echo $this->url(array('controller' => 'assignment', 'action' => 'detail', 'pid' => $project_id, 'id' => $project_ip_user_id), null, true)?>"><?php echo $oObj['username_list']?></a>
																	</td>
																	<td width="33%">
																		<?php echo $oObj['ip_address_list']?>
																	</td>
																	<td width="33%"><?php echo $oObj['mnemonics_list']?></td>
																</tr>
															<?php
																endforeach;
															endif;
															?>
														</tbody>
													</table>
												</div>
											</div>
										<?php echo $this->paginationControl($this->paginator, 
								        							'Sliding',
                                    								'/partials/pagination.phtml', $this->paginatorParams); ?>
							</div>
							<br>
						</div>
					</form>
				</div>
				<?php }?>
				<!-- project Assignment Information -->
			</div>
			<script>
				showChangeMenuTab();
			</script>