				<?php $oCommon = new CommonController();
				$bChkIpAddressInsert = $oCommon->checkPermission('IPADDRESS', 'f_insert');
				$bChkIpAddressUpdate = $oCommon->checkPermission('IPADDRESS', 'f_update');?>
				<div id="show" class="bodycontainer">
				<?php 
				$project_id = isset($this->oProject->project_id)?$oCommon->encodeKey($this->oProject->project_id):'';
				$url = $this->url(array('controller' => 'ipaddress', 'action' => 'detail', 'pid' => $project_id), null, true);
				include_once APPLICATION_PATH . '/views/scripts/partials/project_viewdetail.phtml';
				?>
				<!-- Client Spreadsheet Information -->
				<?php include_once 'menu.phtml';?>
				<div>
					<div id="rwb" class="rwb" style="margin:0 !important">
					<?php
					$url = $this->url(array('controller' => 'ipaddress', 'action' => 'detail', 'pid' => $project_id), null, true);
					$attributes = array('METHOD'=>'post', 'ACTION'=> $url);
					echo $this->form('frmDetail', $attributes);
					echo $this->form->getElement('id');
					echo $this->form->getElement('pid');
					?>
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tbody>
								<tr>
									<td height="30" class="title hline" style="padding-left:10px"> 
										IP Address Information
									</td>
								</tr>
							</tbody>
						</table>
						<div>
							<table class="secContent" width="95%" border="0" cellspacing="1" cellpadding="0">
								<tbody width="100%">
									<tr>
										<td class="label" width="15%">*IP Address</td>
										<td class="element" width="28%">
										<?php echo $this->form->getElement('ip_address'); ?>
										</td>
										<td class="label" width="16%">URL</td>
										<td class="element" width="27%">
										<?php echo $this->form->getElement('url'); ?>
										</td>
									</tr>
									<tr>
										<td class="label" width="15%">Mnemonics</td>
										<td class="element" width="28%">
										<?php echo $this->form->getElement('mnemonics'); ?>
										</td>
										<td class="label" width="16%">Owner Name</td>
										<td class="element" width="27%">
										<?php echo $this->form->getElement('owner_name'); ?>
										</td>
									</tr>
								</tbody>
							</table>
							<?php 
							$bSave = false;
							if ($this->id) {
								if ($bChkIpAddressUpdate == true){
									$bSave = true;
								}
							} else {
								if ($bChkIpAddressInsert == true) {
									$bSave = true;
								}
							}
							if ($bSave == true) {?>
							<p></p>
							<table width="95%" border="0" cellpadding="0" cellspacing="0">
								<tbody>
									<tr>
										<td align="right">
											<?php echo $this->form->getElement('submit-button'); ?>
										</td>
									</tr>
								</tbody>
							</table>
							<?php }?>
						</div>
					</form>
				</div>
				<!-- project NMAP Information -->
				
			</div>
		</div>
		<script>
			showChangeMenuTab();
		</script>