				<div id="show" class="bodycontainer">
				<div id="rwb" class="rwb">
					<?php
					$url = $this->url(array('controller' => 'user', 'action' => 'changepass'), null, true);
					$attributes = array('METHOD'=>'post', 'ACTION'=> $url);
					echo $this->form('frmChangePass', $attributes);
					?>
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tbody>
								<tr>
									<td height="30" class="title hline" style="padding-left:10px"> 
										Change Password
									</td>
								</tr>
							</tbody>
						</table>
						<p></p>
						<div id="secDivSolution Information">
							<table id="secContentSolution Information" class="secContent" width="95%" border="0" cellspacing="1" cellpadding="0">
								<tbody width="100%">
									<tr id="row0_Solution Information">
										<td width="30%" class="label">*Old Password:</td>
										<td width="70%" class="element">
											<?php echo $this->form->getElement('password'); ?>
										</td>
									</tr>
									<tr id="row1_Solution Information">
										<td width="30%" class="label">*New Password:</td>
										<td width="70%" class="element">
											<?php echo $this->form->getElement('new_password'); ?>
										</td>
									</tr>
									<tr id="row1_Solution Information">
										<td width="30%" class="label">*Confirm New Password:</td>
										<td width="70%" class="element">
											<?php echo $this->form->getElement('confirm_password'); ?>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<p></p>
						<table width="95%" border="0" cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td align="right">
										<?php echo $this->form->getElement('submit-button'); ?>
									</td>
								</tr>
							</tbody>
						</table>
						<p></p>
					</form>
				</div>
			</div>
			<script>
				showChangeMenuTab();
				bindMoT('lvTred');
			</script>