				<?php 
				$oCommon = new CommonController();
				$bChkUserInsert = $oCommon->checkPermission('USER', 'f_insert');
				$bChkUserUpdate = $oCommon->checkPermission('USER', 'f_update');
				$bChkUserDelete = $oCommon->checkPermission('USER', 'f_delete');
				?>
				<script type="text/javascript">
					$(document).ready(function() {
						<?php if ($bChkUserInsert == false) {?>
						    $("#btnCreateNew").attr('disabled', 'disabled');
						<?php }?>
						<?php if ($bChkUserDelete == false) {?>
						    $("#btnDelete").attr('disabled', 'disabled');
						    $("input[type='checkbox']").attr('disabled', 'disabled');
						<?php }?>
						<?php if ($bChkUserUpdate == false) {?>
						    $("input[name='btnChangePassword']").each(function(i) {
					            $(this).attr('disabled', 'disabled');
					        });
						<?php }?>
					});
				</script>
				<div id="show" class="bodycontainer">
				<?php
					$url = $this->url(array('controller' => 'user', 'action' => 'index', 'cpage' => $this->countperpage), null, true);
					?>	
					<form name="frmSearch" id="frmSearch" method="POST" action="<?php echo $url?>">		
						<?php echo $this->formHidden('hidDel');?>
						<script>
							function doDelete(){
								var frm = document.frmSearch;
								frm.hidDel.value = selectChecked(document.frmSearch);
								frm.action = "<?php echo $url;//$this->url(array('controller' => 'user', 'action' => 'index'), null, true)?>";
								frm.submit();
							}
						</script>
					<input type="hidden" id="advSearch_name_4" name="advSearch_name_4" value="EMAIL::25::CrmLeadDetails::100::Email::T">
					<div class="idForCVpadding" style="width: 1024px; ">
						<div class="listviewBorder">
							<div class="listviewButtonLayer" style="width: 1024px; ">
								<div class="pwie">
									<table width="100%" border="0" cellpadding="0" cellspacing="0" class="lvblayerTable secContentbb">
										<tbody>
											<tr>
												<td>
													<table border="0" cellspacing="0" cellpadding="0" align="left">
														<tbody>
															<tr>
																<td class="pL10"> 
																	<input type="button" id="btnDelete" name="btnDelete" class="button" value="Delete" onclick="doDelete()">
																</td>
																<td class="pL10">
																	<input type="button" id="btnCreateNew" name="btnCreateNew" class="button createNewBtn" value="New User" onclick="location.href='<?php echo $this->url(array('controller' => 'user', 'action' => 'detail'), null, true); ?>'">
																</td>
															</tr>
														</tbody>
													</table>
												</td>
												 
												<td width="10"> 
											<img src="<?php echo $this->baseUrl().'/public/images/spacer.gif';?>" class="advancedsearch floatR" border="0" align="absmiddle" title="Search" onclick="javascript:callAdvSearch('User')"></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<table width="100%" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
									<tbody>
										<tr id="advancedSearch_showpickId_User" height="35" width="100%" style="display:none;">
											<td colspan="5">
												<table border="0" width="100%" style="padding:5px">
													<tr>
														<td width="15%">User Name</td>
														<td width="28%">
															<?php echo $this->form->getElement('username_search'); ?>
														</td>
														<td width="16%">Email</td>
														<td width="27%">
															<?php echo $this->form->getElement('email_search'); ?>
														</td>
													</tr>
													<tr>
														<td width="15%">Address</td>
														<td width="28%">
															<?php echo $this->form->getElement('address_search'); ?>
														</td>
														<td width="16%">Phone</td>
														<td width="27%">
															<?php echo $this->form->getElement('phone_search'); ?>
														</td>
													</tr>
													</table>
												</td>
												<td style="vertical-align: bottom; padding-bottom:5px">
													<?php echo $this->form->getElement('button-search'); ?>
												</td>
											</tr>
											</table>							
											<div class="header">
												<div style="width: 1008px;">
													<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
														<thead>
															<tr class="tableHeadBg">
																<td width="2%">
																	<input type="checkbox" name="allcheck" onclick="selectAll(document.frmSearch)">
																</td> 
																<td width="16%">User Name</td>
																<td width="24%">Email</td>
																<td width="20%">Address</td>
																<td width="18%">Phone</td>
																<td width="20%"></td>
															</tr>
														</thead>
													</table>
												</div>
												<div class="content">
													<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
														<tbody id="lvTred">
															<?php 
															if (count($this->paginator)):
															$i=1;
															foreach ($this->paginator as $oObj):
															$user_id = $oCommon->encodeKey($oObj['user_id']);
															?>
															<tr id="item<?php echo $i?>" class="tdout">
																<td width="2%">
																	<input type="checkbox" name="chk" value="<?php echo $user_id?>">
																</td>
																<td width="16%"> 
																	<a id="listView_item<?php echo $i?>" class="link" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'detail', 'id' => $user_id), null, true); ?>"><?php echo $oObj['username']?></a>
																</td>
																<td width="24%">
																	<a class="green" href="mailto:<?php echo $oObj['email']?>"><?php echo $oObj['email']?></a>
																</td>
																<td width="20%"><?php echo $oObj['address']?></td>
																<td width="18%"><?php echo $oObj['phone']?></td> 
																<td width="20%">
																	<div align="center" id="divitem<?php echo $i?>" class="indIcon" style="visibility: hidden; ">
																		<input type="button" id="btnChangePassword" name="btnChangePassword" class="btn ChangePasswordBtn" value="Change Password" onclick="javascript:location.href='<?php echo $this->url(array('controller' => 'user', 'action' => 'adchangepass', 'uid' => $user_id), null, true); ?>'">
																	</div>
																</td>
															</tr>
														<?php
															$i++;
															endforeach;
														endif;
														?>
													</tbody>
												</table>
											</div>
										</div>		
							<?php echo $this->paginationControl($this->paginator, 
							        							'Sliding',
                                    							'/partials/pagination.phtml', $this->paginatorParams); ?>
						</div>
						<br>
					</div>
				</form>
			</div>
		<script>
			showChangeMenuTab();
			bindMoT('lvTred');
		</script>