			<?php 		
			$oCommon = new CommonController();
			$bChkProjectInsert = $oCommon->checkPermission('PROJECT', 'f_insert');
			$bChkProjectUpdate = $oCommon->checkPermission('PROJECT', 'f_update');
			$bChkProjectDelete = $oCommon->checkPermission('PROJECT', 'f_delete');
			$bChkClientUpdate = $oCommon->checkPermission('CLIENT', 'f_update');
			?>
			<script type="text/javascript">
				$(document).ready(function() {
					<?php if ($bChkProjectInsert == false) {?>
					    $("#btnCreateNew").attr('disabled', 'disabled');
					<?php }?>
					<?php if ($bChkProjectDelete == false) {?>
					    $("#btnDelete").attr('disabled', 'disabled');
					    $("input[type='checkbox']").attr('disabled', 'disabled');
					<?php }?>
					$( "#start_date_search" ).datepicker({ dateFormat: 'mm/dd/yy' });
				});
			</script>
			<input id="module" type="hidden" name="module" value="Projects">
			<div id="show" class="bodycontainer">
				<?php
					$url = $this->url(array('controller' => 'project', 'action' => 'index', 'cpage' => $this->countperpage), null, true);
					?>	
					<form name="frmSearch" id="frmSearch" method="POST" action="<?php echo $url?>">		
						<?php echo $this->formHidden('hidDel');?>
						<script>
							function doDelete(){
								var frm = document.frmSearch;
								frm.hidDel.value = selectChecked(document.frmSearch);
								frm.action = "<?php echo $url;//$this->url(array('controller' => 'project', 'action' => 'index'), null, true)?>";
								frm.submit();
							}
						</script>
					<input type="hidden" id="advSearch_name_4" name="advSearch_name_4" value="EMAIL::25::CrmLeadDetails::100::Email::T">
					<div class="idForCVpadding" style="width: 1024px; ">
						<div class="listviewBorder">
							<div class="listviewButtonLayer" style="width: 1024px; ">
								<div class="pwie">
									<table width="100%" border="0" cellpadding="0" cellspacing="0" class="lvblayerTable secContentbb">
										<tbody>
											<tr>
												<td>
													<table border="0" cellspacing="0" cellpadding="0" align="left">
														<tbody>
															<tr>
																<td class="pL10"> 
																	<input type="button" id="btnDelete" name="btnDelete" class="button" value="Delete" onclick="doDelete()">
																</td>
																<td class="pL10">
																	<input type="button" id="btnCreateNew" name="btnCreateNew" class="button createNewBtn" value="New Project" onclick="javascript:location.href='<?php echo $this->url(array('controller' => 'project', 'action' => 'detail'), null, true); ?>'">
																</td>
															</tr>
														</tbody>
													</table>
												</td>   
												<td width="10"> 
											<img src="<?php echo $this->baseUrl().'/public/images/spacer.gif';?>" class="advancedsearch floatR" border="0" align="absmiddle" title="Search" onclick="javascript:callAdvSearch('Projects')"></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<table width="100%" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
								<tbody>
									<tr id="advancedSearch_showpickId_Projects" height="35" width="100%" style="display:none;">
										<td colspan="5">
											<table border="0" width="100%" style="padding:5px">
												<tr>
													<td width="15%">Client Name</td>
													<td width="28%"><?php echo $this->form->getElement('client_name_search'); ?></td>
													<td width="16%">Project Name</td>
													<td width="27%"><?php echo $this->form->getElement('project_name_search'); ?></td>
												</tr>
												<tr>
													<td width="15%">Start Date</td>
													<td width="28%"><?php echo $this->form->getElement('start_date_search'); ?></td>
													<td width="50%" colspan="2"></td>
												</tr>
											</table>
										</td>
										<td style="vertical-align: bottom; padding-bottom:5px">
											<?php echo $this->form->getElement('button-search'); ?>
										</td>
									</tr>
								<tbody>
							</table>
							<div class="header">
								<div style="width: 1008px;">
									<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
										<thead>
											<tr class="tableHeadBg">
												<td width="2%">
													<input type="checkbox" name="allcheck" onclick="selectAll(document.frmSearch)">
												</td> 
												<td width="35%">Client Name</td>
												<td width="35%">Project Name</td>
												<td width="14%">Start Date</td>
												<td width="14%">Owner</td>
											</thead>
										</table>
									</div>
									<div class="content">
										<table width="1008px" border="0" cellpadding="0" cellspacing="0" id="listViewTable" class="listview">
											<tbody id="lvTred">
												<?php 
												if (count($this->paginator)):
													$i=1;
													foreach ($this->paginator as $oObj):
													$client_id = $oCommon->encodeKey($oObj['client_id']);
													$project_id = $oCommon->encodeKey($oObj['project_id']);
													$date = date_create($oObj['start_date']);
													$start_date = $date->format('m/d/Y');
													?>
													<tr id="item<?php echo $i?>" class="tdout">
														<td width="2%">
															<input type="checkbox" name="chk" value="<?php echo $project_id?>">
														</td>
														<td width="35%"> 
															<a id="listView_item<?php echo $i?>" class="link" href="<?php echo $this->url(array('controller' => 'client', 'action' => 'detail', 'cid' => $client_id), null, true); ?>"><?php echo $oObj['client_name']?></a>
														</td>
														<td width="35%"> 
															<a id="listView_item<?php echo $i?>" class="link" href="<?php echo $this->url(array('controller' => 'ipaddress', 'action' => 'index', 'pid' => $project_id), null, true); ?>"><?php echo $oObj['project_name']?></a>
														</td>
														<td width="14%"><?php echo $start_date?></td>
														<td width="14%"><?php echo $oObj['user_create']?></td>
													</tr>
												<?php
													$i++;
													endforeach;
												endif;
												?>
											</tbody>
										</table>
									</div>
								</div>			
							<?php echo $this->paginationControl($this->paginator, 
							        							'Sliding',
                                    							'/partials/pagination.phtml', $this->paginatorParams); ?>
						</div>
						<br>
					</div>
				</form>
			</div>
			<script>
				showChangeMenuTab();
				bindMoT('lvTred');
			</script>